# Generated by Django 5.1.3 on 2024-11-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='captions',
        ),
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
