# Generated by Django 5.1.3 on 2024-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_captions_photo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
